/*
 * This source file was generated by the Gradle 'init' task
 */
package fn10.bedrockr;

import fn10.bedrockr.addons.source.SourceWorkspaceFile;
import fn10.bedrockr.rendering.BlockTextures;
import fn10.bedrockr.rendering.RenderHandler;
import fn10.bedrockr.utils.ErrorShower;
import fn10.bedrockr.utils.RFileOperations;
import fn10.bedrockr.utils.SettingsFile;
import fn10.bedrockr.utils.http.Format1Latest;
import fn10.bedrockr.utils.logging.RLogFilter;
import fn10.bedrockr.utils.logging.RLogFormatter;
import fn10.bedrockr.utils.logging.RLogHandler;
import fn10.bedrockr.windows.RLaunchPage;
import fn10.bedrockr.windows.RSplashScreen;
import fn10.bedrockr.windows.laf.BedrockrDark;
import javafx.application.Platform;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import javafx.scene.web.WebEngine;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.FocusEvent.Cause;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.logging.*;

import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatLaf;
import com.google.gson.Gson;
import com.google.gson.internal.LinkedTreeMap;

public class Launcher {

    public static String VERSION = "a1.4";
    public static int CHECKVERSION = 6;
    public static Image ICON;

    public static WebEngine BLOCKLY_MINI_WEBENGINE;

    public static List<Image> ICONS = new ArrayList<Image>();

    public static Dimension LAUNCH_WINDOW_SIZE = new Dimension(600, 400);
    public static Logger LOG = Logger.getLogger("bedrockR");
    public static HttpClient client = HttpClient.newBuilder().build();

    public static void main(String[] args) {
        String ver = System.getProperty("java.version");
        if (ver.startsWith("1.")) {
            JOptionPane.showConfirmDialog(null, "Woah! This version of java is out of date.\n\nYour version: " + ver
                    + "\n Required version: 25.0.0", "Java error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (Integer.parseInt(ver.substring(0, 2)) < 25) {
            JOptionPane.showConfirmDialog(null, "Woah! This version of java is out of date.\n\nYour version: " + ver
                    + "\n Required version: 25.0.0", "Java error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            ICON = ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui/Icon_huge.png"));
            /*
             * ICONS = new Image[] {
             * ICONS.add(ImageIO.read(Launcher.class
             * .getResourceAsStream("/ui/Icon_16.png")));
             * ICONS.add(ImageIO.read(Launcher.class
             * .getResourceAsStream("/ui/Icon_27.png")));
             * ICONS.add(ImageIO.read(Launcher.class
             * .getResourceAsStream("/ui/Icon_32.png")));
             * ICONS.add(ImageIO.read(Launcher.class
             * .getResourceAsStream("/ui/Icon_64.png")));
             * ICONS.add(ImageIO.read(Launcher.class
             * .getResourceAsStream("/ui/Icon_128.png")));
             * ICONS.add(ImageIO.read(Launcher.class
             * .getResourceAsStream("/ui/Icon_256.png")));
             * ICONS.add(ImageIO.read(Launcher.class
             * .getResourceAsStream("/ui/Icon_huge.png")));
             * };
             */
        } catch (Exception e) {
            e.printStackTrace();
            ErrorShower.showError(null, "Failed to load icon(s)", "IO Error", e);
        }
        RSplashScreen loading = new RSplashScreen();
        loading.ProgressText.setText("Loading icon...");

        // set up logging
        loading.ProgressText.setText("Setting up logging...");
        String logloc = RFileOperations.getBaseDirectory(loading, File.separator + "logs").getAbsolutePath()
                + File.separator + "bedrockR-log-"
                + System.currentTimeMillis() + ".log";

        for (var h : LOG.getHandlers()) {
            LOG.removeHandler(h);
            h.close();
        }
        LOG.setUseParentHandlers(false);
        LOG.setLevel(Level.FINE);
        LOG.addHandler(new RLogHandler());

        // try to add file handler
        try {
            Handler fileHandler = new FileHandler(logloc, 2000, 1, true);
            fileHandler.setFormatter(new RLogFormatter());
            fileHandler.setFilter(new RLogFilter());
            LOG.addHandler(fileHandler);
        } catch (SecurityException | IOException e) {
            e.printStackTrace();
        }

        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {
                for (var h : LOG.getHandlers()) {
                    h.close();
                }
            }
        });

        // log stuff
        LOG.info("Logging to " + logloc);
        LOG.info("Base Path: " + RFileOperations.getBaseDirectory(loading).getAbsolutePath());
        LOG.info("Launch Args: " + String.join(",", args));
        LOG.info(MessageFormat.format("bedrockR version: {0}, Java version: {1}, JVM: {2}", VERSION, Runtime.version(),
                System.getProperty("java.vm.name")));

        // setup theme

        loading.ProgressText.setText("Setting up theme...");
        FlatLaf.registerCustomDefaultsSource("fn10.bedrockr.windows.laf");

        try {
            GraphicsEnvironment.getLocalGraphicsEnvironment()
                    .registerFont(
                            Font.createFont(Font.TRUETYPE_FONT, Launcher.class.getResourceAsStream("/ui/font.otf")));
            BedrockrDark.setup();
        } catch (Exception e) {
            e.printStackTrace();
            ErrorShower.showError(loading, "failed to load theme/font " + e.getMessage(), "FlatLaf Error / Font Error",
                    e);
        }

        // try to see if this version is out of date
        loading.ProgressText.setText("Checking for updates...");
        try {
            HttpRequest req = HttpRequest.newBuilder()
                    .uri(new URI("https://raw.githubusercontent.com/xFN10x/bedrockR/refs/heads/master/latest.json"))
                    .version(HttpClient.Version.HTTP_2).GET().build();

            HttpResponse<String> response = client.send(req, BodyHandlers.ofString());

            Format1Latest serilized = new Gson().fromJson(response.body(), Format1Latest.class);

            if (serilized.LatestVersion > CHECKVERSION && serilized.ShouldUse) {
                int op = JOptionPane.showConfirmDialog(loading, serilized.Message,
                        "Version out of date (" + serilized.CurrentStringVersion + " > " + VERSION + ")",
                        JOptionPane.YES_NO_OPTION);
                if (op == JOptionPane.YES_OPTION) {
                    Desktop.getDesktop().browse(new URI("https://github.com/xFN10x/bedrockR/releases/latest"));
                    System.exit(0);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        loading.ProgressText.setText("Setting up Blockly...");
        try {
            CountDownLatch latch = new CountDownLatch(1);
            Platform.startup(() -> {
                WebEngine webEngine = new WebEngine();
                webEngine.load(Launcher.class.getResource("/blockly/blockly-minimized.html").toExternalForm());
                webEngine.getLoadWorker().stateProperty().addListener(
                        new ChangeListener<Worker.State>() {
                            @Override
                            public void changed(
                                    ObservableValue<? extends javafx.concurrent.Worker.State> observable,
                                    javafx.concurrent.Worker.State oldValue,
                                    javafx.concurrent.Worker.State newValue) {
                                if (newValue == Worker.State.SUCCEEDED) {
                                    // when its loaded, add a referance to java
                                    webEngine
                                            .executeScript(RFileOperations.readResourceAsString("/blockly/blockly.js"));
                                    BLOCKLY_MINI_WEBENGINE = webEngine;
                                    latch.countDown();
                                } else if (newValue == Worker.State.FAILED) {
                                    Exception ex = new Exception("Blockly pane failed to load.");

                                    ex.printStackTrace();
                                    loading.setAlwaysOnTop(false);
                                    ErrorShower.showError(loading, "Blockly Pane failed to load.", ex);
                                } else {
                                    Exception ex = new Exception("Blockly pane failed to load.");
                                    Launcher.LOG.info("Unknown state: " + newValue);
                                    ErrorShower.showError(loading, "Blockly Pane failed to load. Unknown state.", ex);
                                }

                            }
                        });
            });
            try {
                if (!latch.await(10000, TimeUnit.MILLISECONDS)) {
                    loading.setAlwaysOnTop(false);
                    JOptionPane.showMessageDialog(loading,
                            "Failed to load blockly; you will not be able to build scripts!", "Blockly Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            // this throws if javafx is already started. idk how to check if it is
        }

        loading.ProgressText.setText("Setting up 3D...");
        RenderHandler.startup();

        loading.ProgressText.setText("Downloading Block textures...");
        HttpRequest latestMCDataVerReq = HttpRequest.newBuilder()
                .uri(URI.create("https://api.github.com/repos/PrismarineJS/minecraft-data/releases/latest"))
                .version(HttpClient.Version.HTTP_2).GET().build();
        try {
            HttpResponse<String> response = client.send(latestMCDataVerReq, BodyHandlers.ofString());
            SettingsFile settings = SettingsFile
                    .load(loading);
            if (settings.LastTimeBlockTexturesCachedPrismarineJSMCDataVersionID == null
                    || settings.LastTimeBlockTexturesCachedPrismarineJSMCDataVersionID != ((Double) new Gson()
                            .fromJson(response.body(), LinkedTreeMap.class).get("id")).longValue()) {
                try {
                    BlockTextures.downloadAllBlockTextures(loading).await();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            return;
        }

        loading.ProgressText.setText("Checking if opening workspace...");
        if (args.length >= 1) {
            File file;
            if ((file = Path.of(args[0]).toFile()).exists()) {
                if (file.getPath().endsWith(RFileOperations.WPFFILENAME)) {
                    try {
                        RFileOperations.openWorkspace(loading,
                                new SourceWorkspaceFile(Files.readString(file.toPath())));
                        return;
                    } catch (IOException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(loading, "Couldn't open up that WPF file!");
                    }
                }
            }
        }

        // open app
        loading.ProgressText.setText("Launching...");
        SwingUtilities.invokeLater(() -> {
            RLaunchPage launch = new RLaunchPage(LAUNCH_WINDOW_SIZE);
            launch.setVisible(true);
            loading.setVisible(false);
            launch.requestFocus(Cause.ACTIVATION);
        });
    }
}
