/*
 * This source file was generated by the Gradle 'init' task
 */
package fn10.bedrockr;

import fn10.bedrockr.utils.RFileOperations;
import fn10.bedrockr.utils.logging.RLogFilter;
import fn10.bedrockr.utils.logging.RLogFormatter;
import fn10.bedrockr.utils.logging.RLogHandler;
import fn10.bedrockr.windows.RLaunchPage;
import fn10.bedrockr.windows.laf.BedrockrDark;

import java.awt.*;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.*;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

public class Launcher {

    public static String VERSION = "a1.0";
    public static ImageIcon ICON = new ImageIcon(Launcher.class.getResource("/ui/Icon.png"));

    public static Dimension LAUNCH_WINDOW_SIZE = new Dimension(600, 400);
    public static Logger LOG = Logger.getLogger("bedrockR");

    public static void main(String[] args) {
        // set up logging
        String logloc = System.getProperty("java.io.tmpdir")
                + System.currentTimeMillis() + "\\bedrockR-log" + System.currentTimeMillis() + ".txt";

        for (var h : LOG.getHandlers()) {
            LOG.removeHandler(h);
        }
        LOG.setUseParentHandlers(false);
        LOG.setLevel(Level.FINE);
        LOG.addHandler(new RLogHandler());

        // try to add file handler
        try {

            Handler fileHandler = new FileHandler(logloc, 2000, 5);
            fileHandler.setFormatter(new RLogFormatter());
            LOG.addHandler(fileHandler);

            fileHandler.setFilter(new RLogFilter());
        } catch (SecurityException | IOException e) {
            e.printStackTrace();
        }

        // log stuff
        LOG.info("Logging to " + logloc);
        LOG.info(RFileOperations.getBaseDirectory(null).getAbsolutePath());
        LOG.info(MessageFormat.format("bedrockR version: {0}, Java version: {1}, JVM: {2}", VERSION, Runtime.version(),
                System.getProperty("java.vm.name")));

        // setup theme

        // FlatLaf.registerCustomDefaultsSource("fn10.bedrockr.windows.laf" );
        try {
            BedrockrDark.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }
        // open app
        SwingUtilities.invokeLater(() -> {
            new RLaunchPage(LAUNCH_WINDOW_SIZE);
        });
    }
}
