/*
 * This source file was generated by the Gradle 'init' task
 */
package fn10.bedrockr;

import fn10.bedrockr.utils.ErrorShower;
import fn10.bedrockr.utils.RFileOperations;
import fn10.bedrockr.utils.logging.RLogFilter;
import fn10.bedrockr.utils.logging.RLogFormatter;
import fn10.bedrockr.utils.logging.RLogHandler;
import fn10.bedrockr.windows.RLaunchPage;
import fn10.bedrockr.windows.laf.BedrockrDark;
import javafx.application.Platform;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.*;

import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatLaf;

public class Launcher {

    public static String VERSION = "a1.0";
    public static Image ICON;

    public static java.util.List<Image> ICONS = new ArrayList<Image>();
    static {
        // System.out.println("pathsep is " + File.separator);
        try {
            ICON = ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_huge.png"));
            // ICONS = new Image[] {
            ICONS.add(ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_16.png")));
            ICONS.add(ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_27.png")));
            ICONS.add(ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_32.png")));
            ICONS.add(ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_64.png")));
            ICONS.add(ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_128.png")));
            ICONS.add(ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_256.png")));
            ICONS.add(ImageIO.read(Launcher.class
                    .getResourceAsStream("/ui" + "/Icon_huge.png")));
            // };
        } catch (Exception e) {
            e.printStackTrace();
            ErrorShower.showError(null, "Failed to load icon(s)", "IO Error", e);
        }
    }

    public static Dimension LAUNCH_WINDOW_SIZE = new Dimension(600, 400);
    public static Logger LOG = Logger.getLogger("bedrockR");

    public static void main(String[] args) {
        // start up javafx
        Platform.startup(() -> {
        });
        // set up logging
        String logloc = RFileOperations.getBaseDirectory(null, File.separator + "logs").getAbsolutePath()
                + File.separator + "bedrockR-log-"
                + System.currentTimeMillis() + ".log";

        for (var h : LOG.getHandlers()) {
            LOG.removeHandler(h);
            h.close();
        }
        LOG.setUseParentHandlers(false);
        LOG.setLevel(Level.FINE);
        LOG.addHandler(new RLogHandler());

        // try to add file handler
        try {

            Handler fileHandler = new FileHandler(logloc, 2000, 1, true);
            fileHandler.setFormatter(new RLogFormatter());
            fileHandler.setFilter(new RLogFilter());
            LOG.addHandler(fileHandler);
        } catch (SecurityException | IOException e) {
            e.printStackTrace();
        }

        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {
                for (var h : LOG.getHandlers()) {
                    // LOG.removeHandler(h);
                    h.close();
                }
            }
        });

        // log stuff
        LOG.info("Logging to " + logloc);
        LOG.info("Base Path: " + RFileOperations.getBaseDirectory(null).getAbsolutePath());
        LOG.info("Launch Args: " + String.join(",", args));
        LOG.info(MessageFormat.format("bedrockR version: {0}, Java version: {1}, JVM: {2}", VERSION, Runtime.version(),
                System.getProperty("java.vm.name")));
        // LOG.info(System.getenv("LOCALAPPDATA"));

        // setup theme

        FlatLaf.registerCustomDefaultsSource("fn10.bedrockr.windows.laf");

        try {
            GraphicsEnvironment.getLocalGraphicsEnvironment()
                .registerFont(Font.createFont(Font.TRUETYPE_FONT, Launcher.class.getResourceAsStream("/ui/font.otf")));
            BedrockrDark.setup();
        } catch (Exception e) {
            e.printStackTrace();
            ErrorShower.showError(null, "failed to load theme/font " + e.getMessage(), "FlatLaf Error / Font Error", e);
        }
        
        // open app
        SwingUtilities.invokeLater(() -> {
            var launch = new RLaunchPage(LAUNCH_WINDOW_SIZE);
            launch.setVisible(true);
        });
    }
}
