name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,	ubuntu-24.04-arm]
    
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build Portable
      run: ./gradlew jpackagePORTABLE --info

    - name: Upload Portable   
      uses: actions/upload-artifact@v4
      with:
        name: PSPTools-${{matrix.os}}-portable
        path: build/builtDist  

    - name: Build Normal
      run: ./gradlew jpackage --info

    - name: Upload Normal   
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: PSPTools-${{matrix.os}}
        path: build/builtDist  


    - uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        if-no-files-found: error
        name: bedrockR-a.1.1.jar
        path: build/builtJars/bedrockR-a1.1-all.jar
      


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
