# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = light


@background = #f0f0f0


control = #dedede

*.borderColor = #182f05

@foreground = #202020

@disabledBackground = #6eff79